"""Generate and update the central agents.md index file."""

from datetime import datetime
from pathlib import Path

from slidesmd.extractor import PresentationMeta


INDEX_FILENAME = "agents.md"


def build_index(presentations: list[PresentationMeta], output_dir: Path) -> Path:
    """Write a fresh agents.md from all presentation metadata."""
    output_path = output_dir / INDEX_FILENAME
    content = _render(presentations)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _render(presentations: list[PresentationMeta]) -> str:
    lines = [
        "# Presentations Index",
        "",
        f"_Auto-generated by slidesmd on {datetime.now().strftime('%Y-%m-%d %H:%M')}_",
        "",
        "---",
        "",
    ]

    if not presentations:
        lines.append("_No presentations found yet._")
        return "\n".join(lines)

    for meta in sorted(presentations, key=lambda m: m.title.lower()):
        lines += [
            f"## {meta.title}",
            "",
            f"- **File:** `{meta.file_path}`",
            f"- **Slides:** {meta.slide_count}",
        ]

        if meta.topics:
            lines.append(f"- **Topics:** {', '.join(meta.topics[:5])}")

        if meta.todos:
            lines.append("- **To-dos:**")
            for todo in meta.todos:
                lines.append(f"  - {todo}")

        if meta.slide_summaries:
            lines += ["", "**Slide content:**", ""]
            for i, (slide_title, body) in enumerate(meta.slide_summaries, 1):
                heading = slide_title or f"Slide {i}"
                lines.append(f"- **{heading}**" + (f": {body}" if body else ""))

        lines += ["", "---", ""]

    return "\n".join(lines)
